### ISSUE TITLE
Installing the lifelines library

### ISSUE THREAD

**Issue by ali-fahmi** [opensafely/jupyter-docker#11]
I have tried to install and use the lifelines library. Although it seems to be installed, an error pops up when running the code in opensafely, saying: ModuleNotFoundError: No module named 'lifelines' (see https://github.com/opensafely/amr-uom-brit/runs/4398718403?check_suite_focus=true). I wonder if I need to install the library in a certain way (except with pip or conda)? Or is it a problem with the version differences and I need to use an environment maybe?

**Comment by bloodearnest** [comment]
Fixed in #13
